par(mfrow=c(3,2))
plot(as.factor(class)~dd$V1)
plot(as.factor(class)~dd$V2)
plot(as.factor(class)~dd$V3)
plot(as.factor(class)~dd$V4)
plot(as.factor(class)~dd$V5)
plot(as.factor(class)~dd$V6)

par(mfrow=c(3,2))
plot(as.factor(class)~dd$V7)
plot(as.factor(class)~dd$V8)
plot(as.factor(class)~dd$V9)
plot(as.factor(class)~dd$V10)
plot(as.factor(class)~dd$V11)
plot(as.factor(class)~dd$V12)

par(mfrow=c(3,2))
plot(as.factor(class)~dd$V13)
plot(as.factor(class)~dd$V14)
plot(as.factor(class)~dd$V15)
plot(as.factor(class)~dd$V16)
plot(as.factor(class)~dd$V17)
plot(as.factor(class)~dd$V18)

par(mfrow=c(3,2))
plot(as.factor(class)~dd$V19)
plot(as.factor(class)~dd$V20)
plot(as.factor(class)~dd$V21)
plot(as.factor(class)~dd$V22)
plot(as.factor(class)~dd$V23)
plot(as.factor(class)~dd$V24)
